# Generated by Django 3.1.5 on 2026-02-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='reaction',
            field=models.CharField(choices=[('like', 'like'), ('love', 'love'), ('clap', 'clap'), ('insightful', 'insightful'), ('dislike', 'dislike')], default='like', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('active', 'active')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='blog.blog')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('post', 'date')},
            },
        ),
    ]
